import type { IRCServer, IRCChannel, IRCMessage, IRCUser, MessageType } from './types'

let msgIdCounter = 0
function msgId() {
  return `msg-${++msgIdCounter}`
}

function makeMsg(
  channelId: string,
  serverId: string,
  type: MessageType,
  nickname: string,
  content: string,
  minutesAgo: number,
  isHighlight = false
): IRCMessage {
  return {
    id: msgId(),
    channelId,
    serverId,
    type,
    nickname,
    content,
    timestamp: new Date(Date.now() - minutesAgo * 60000),
    isHighlight,
  }
}

const freenodeUsers: IRCUser[] = [
  { nickname: 'rustacean', username: 'rust', realName: 'Rust Dev', hostmask: 'rust@user/rustacean', modes: ['@'], isOp: true, isVoiced: false, isAway: false },
  { nickname: 'nodemaster', username: 'node', realName: 'Node Developer', hostmask: 'node@gateway/web', modes: ['+'], isOp: false, isVoiced: true, isAway: false },
  { nickname: 'pythonicgal', username: 'py', realName: 'Python Fan', hostmask: 'py@unaffiliated/pythonicgal', modes: [], isOp: false, isVoiced: false, isAway: false },
  { nickname: 'goopher', username: 'go', realName: 'Go Enthusiast', hostmask: 'go@user/goopher', modes: ['+'], isOp: false, isVoiced: true, isAway: false },
  { nickname: 'kerneldev', username: 'kern', realName: 'Linux Hacker', hostmask: 'kern@kernel.org/dev', modes: ['@'], isOp: true, isVoiced: false, isAway: false },
  { nickname: 'csswhiz', username: 'css', realName: 'CSS Magician', hostmask: 'css@unaffiliated/csswhiz', modes: [], isOp: false, isVoiced: false, isAway: true },
  { nickname: 'devopsguru', username: 'devops', realName: 'DevOps Engineer', hostmask: 'devops@cloud/gcp', modes: [], isOp: false, isVoiced: false, isAway: false },
  { nickname: 'sqlninja', username: 'sql', realName: 'Database Admin', hostmask: 'sql@user/sqlninja', modes: ['+'], isOp: false, isVoiced: true, isAway: false },
  { nickname: 'hackernews', username: 'hn', realName: 'HN Reader', hostmask: 'hn@gateway/tor', modes: [], isOp: false, isVoiced: false, isAway: false },
  { nickname: 'typescripter', username: 'ts', realName: 'TS Advocate', hostmask: 'ts@unaffiliated/typescripter', modes: [], isOp: false, isVoiced: false, isAway: false },
]

const libera1Users: IRCUser[] = [
  { nickname: 'archbtw', username: 'arch', realName: 'Arch User', hostmask: 'arch@user/archbtw', modes: ['@'], isOp: true, isVoiced: false, isAway: false },
  { nickname: 'vimwarrior', username: 'vim', realName: 'Vim Power User', hostmask: 'vim@user/vimwarrior', modes: ['+'], isOp: false, isVoiced: true, isAway: false },
  { nickname: 'emacsgod', username: 'emacs', realName: 'Emacs Lover', hostmask: 'emacs@gnu.org/emacsgod', modes: [], isOp: false, isVoiced: false, isAway: false },
  { nickname: 'nixfan', username: 'nix', realName: 'NixOS User', hostmask: 'nix@unaffiliated/nixfan', modes: [], isOp: false, isVoiced: false, isAway: false },
  { nickname: 'dockercapt', username: 'dock', realName: 'Container Expert', hostmask: 'dock@docker.io/captain', modes: ['@'], isOp: true, isVoiced: false, isAway: false },
  { nickname: 'k8smaster', username: 'k8s', realName: 'Kubernetes Admin', hostmask: 'k8s@cloud/k8smaster', modes: ['+'], isOp: false, isVoiced: true, isAway: true },
  { nickname: 'gitguru', username: 'git', realName: 'Git Expert', hostmask: 'git@github.com/gitguru', modes: [], isOp: false, isVoiced: false, isAway: false },
  { nickname: 'tmuxer', username: 'tmux', realName: 'Terminal Junkie', hostmask: 'tmux@user/tmuxer', modes: [], isOp: false, isVoiced: false, isAway: false },
]

const efnetUsers: IRCUser[] = [
  { nickname: 'oldschool', username: 'old', realName: 'IRC Veteran', hostmask: 'old@irc.efnet.org/oper', modes: ['@'], isOp: true, isVoiced: false, isAway: false },
  { nickname: 'netadmin', username: 'admin', realName: 'Network Admin', hostmask: 'admin@efnet.org/staff', modes: ['@'], isOp: true, isVoiced: false, isAway: false },
  { nickname: 'scriptkid', username: 'script', realName: 'Script Writer', hostmask: 'script@user/scriptkid', modes: ['+'], isOp: false, isVoiced: true, isAway: false },
  { nickname: 'perlhacker', username: 'perl', realName: 'Perl Developer', hostmask: 'perl@cpan.org/perlhacker', modes: [], isOp: false, isVoiced: false, isAway: false },
  { nickname: 'bsduser', username: 'bsd', realName: 'FreeBSD User', hostmask: 'bsd@freebsd.org/bsduser', modes: [], isOp: false, isVoiced: false, isAway: true },
  { nickname: 'rfcreader', username: 'rfc', realName: 'Protocol Nerd', hostmask: 'rfc@ietf.org/rfcreader', modes: ['+'], isOp: false, isVoiced: true, isAway: false },
]

// --- Freenode Messages ---
const freenodeGeneral: IRCMessage[] = [
  makeMsg('fn-general', 'freenode', 'join', 'devopsguru', 'devopsguru (~devops@cloud.host) has joined #general', 120),
  makeMsg('fn-general', 'freenode', 'message', 'rustacean', 'Hey everyone! Anyone tried the new Rust 2025 edition yet?', 115),
  makeMsg('fn-general', 'freenode', 'message', 'nodemaster', 'Not yet, still wrapping up a Node.js migration at work. Moving from Express to Hono.', 112),
  makeMsg('fn-general', 'freenode', 'message', 'pythonicgal', "I've been experimenting with it. The borrow checker improvements are real.", 109),
  makeMsg('fn-general', 'freenode', 'message', 'goopher', "Speaking of migrations, anyone have a good pattern for graceful shutdown in Go? Here's what I have:", 105),
  makeMsg('fn-general', 'freenode', 'message', 'goopher', '```go\nfunc gracefulShutdown(srv *http.Server) {\n    quit := make(chan os.Signal, 1)\n    signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)\n    <-quit\n    \n    ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)\n    defer cancel()\n    \n    if err := srv.Shutdown(ctx); err != nil {\n        log.Fatal("Server forced to shutdown:", err)\n    }\n    log.Println("Server exiting")\n}\n```', 103),
  makeMsg('fn-general', 'freenode', 'message', 'kerneldev', 'That looks solid. I usually add a health check endpoint that returns 503 during shutdown too.', 100),
  makeMsg('fn-general', 'freenode', 'message', 'devopsguru', "^ This. Your load balancer needs to know you're draining.", 98),
  makeMsg('fn-general', 'freenode', 'message', 'csswhiz', "Off topic but has anyone seen the new CSS anchor positioning? It's in Chrome stable now.", 95),
  makeMsg('fn-general', 'freenode', 'message', 'hackernews', 'Yeah it was on HN yesterday. Popover API + anchor positioning = no more JS tooltips', 92),
  makeMsg('fn-general', 'freenode', 'message', 'typescripter', 'TypeScript 6.0 beta just dropped btw. The new type inference is insane:', 88),
  makeMsg('fn-general', 'freenode', 'message', 'typescripter', '```typescript\n// Before: needed explicit generics\nconst result = pipe<string, number, boolean>(\n  parse,\n  validate,\n  transform\n);\n\n// After: fully inferred!\nconst result = pipe(parse, validate, transform);\n// result is correctly typed as boolean\n```', 86),
  makeMsg('fn-general', 'freenode', 'message', 'rustacean', "That's great! TS keeps getting better. Still prefer Rust for backend though :P", 83),
  makeMsg('fn-general', 'freenode', 'action', 'nodemaster', 'is jealous of Rust compile-time guarantees', 80),
  makeMsg('fn-general', 'freenode', 'message', 'pythonicgal', "Meanwhile Python: `if it works it works` lol", 77),
  makeMsg('fn-general', 'freenode', 'nick_change', 'sqlninja', 'sqlninja is now known as sqlninja_afk', 76),
  makeMsg('fn-general', 'freenode', 'mode', 'ChanServ', 'ChanServ sets mode +o kerneldev', 76),
  makeMsg('fn-general', 'freenode', 'ctcp', 'system', 'CTCP VERSION reply from rustacean: mIRC v7.75 (Windows)', 76),
  makeMsg('fn-general', 'freenode', 'notice', 'ChanServ', 'This channel is logged. https://logs.freenode.example/general', 75),
  makeMsg('fn-general', 'freenode', 'message', 'hackernews', '\x0304,01 BREAKING \x03 \x02New zero-day in OpenSSL\x02 - CVE-2026-0142 - patch \x0309immediately\x03 https://nvd.nist.gov/vuln/detail/CVE-2026-0142', 73),
  makeMsg('fn-general', 'freenode', 'message', 'kerneldev', '\x0303[STATUS]\x03 All servers patched. \x02\x0309OK\x03\x02 | Build: \x0312#4851\x03 | Uptime: \x0311342d 6h\x03', 72),
  makeMsg('fn-general', 'freenode', 'message', 'devopsguru', 'nice use of irc colors lol. here: \x02\x1F\x0313fancy\x03\x1F\x02 and \x0304,08 warning badge \x03', 71),
  makeMsg('fn-general', 'freenode', 'message', 'csswhiz', '\x1DItalic text\x1D and \x02bold text\x02 and \x1Funderline\x1F and \x02\x1F\x1Dall three\x0F back to normal', 71),
  makeMsg('fn-general', 'freenode', 'message', 'sqlninja', 'Anyone seen weird Postgres 17 behavior with CTEs? My recursive query is way slower.', 70),
  makeMsg('fn-general', 'freenode', 'message', 'kerneldev', 'Check if the planner is materializing the CTE. Try `MATERIALIZED` hint.', 68),
  makeMsg('fn-general', 'freenode', 'message', 'sqlninja', '```sql\nWITH RECURSIVE tree AS MATERIALIZED (\n  SELECT id, parent_id, name, 0 AS depth\n  FROM categories\n  WHERE parent_id IS NULL\n  UNION ALL\n  SELECT c.id, c.parent_id, c.name, t.depth + 1\n  FROM categories c\n  JOIN tree t ON c.parent_id = t.id\n)\nSELECT * FROM tree ORDER BY depth, name;\n```', 65),
  makeMsg('fn-general', 'freenode', 'message', 'sqlninja', 'That fixed it! Query went from 2.3s to 45ms. Thanks!', 62),
  makeMsg('fn-general', 'freenode', 'message', 'devopsguru', 'Nice. Postgres planner changes between versions can be sneaky.', 60),
  makeMsg('fn-general', 'freenode', 'message', 'hackernews', 'Cloudflare just open-sourced their Workers runtime. Anyone looking at it? Here is the full announcement post with all the technical details about V8 isolates, the new streaming API, and how they handle cold starts differently from Lambda: https://blog.cloudflare.com/open-sourcing-workerd-the-runtime-powering-cloudflare-workers-with-full-v8-isolate-sandboxing-and-streaming-support-2026?utm_source=hackernews&utm_medium=social&utm_campaign=oss_announcement_q1_2026&ref=hn_discussion_thread_41293847', 55),
  makeMsg('fn-general', 'freenode', 'message', 'goopher', 'Interesting. Wonder how it compares to Deno Deploy. I have been running a fairly complex microservices architecture on Deno Deploy for about six months now and the cold start times are consistently under 50ms which is way better than what we were getting on AWS Lambda, though the lack of some Node.js APIs still bites us occasionally when trying to use certain npm packages that rely on fs or child_process.', 52),
  makeMsg('fn-general', 'freenode', 'part', 'csswhiz', 'csswhiz (~css@design.net) has left #general (heading to lunch)', 50),
  makeMsg('fn-general', 'freenode', 'message', 'kerneldev', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE <-- testing long unbroken string wrapping', 48),
  makeMsg('fn-general', 'freenode', 'message', 'devopsguru', 'Error from prod: `TypeError: Cannot read properties of undefined (reading "metadata") at /app/services/orchestrator/pipeline/stage-executor/transform-handler.ts:847:42` -- anyone seen this before? The full stack trace is in our Sentry dashboard.', 46),
  makeMsg('fn-general', 'freenode', 'message', 'nodemaster', "Been running Deno in prod for 6 months. No complaints honestly.", 45),
  makeMsg('fn-general', 'freenode', 'message', 'typescripter', 'Deno + Fresh is underrated for full-stack TS apps', 42),
  makeMsg('fn-general', 'freenode', 'message', 'rustacean', 'Check this benchmarks link: https://web-frameworks-benchmark.example.com/2026', 38),
  makeMsg('fn-general', 'freenode', 'message', 'pythonicgal', 'FastAPI is still holding its own! Not bad for Python.', 35),
  makeMsg('fn-general', 'freenode', 'message', 'kerneldev', "Numbers are meaningless without context. What's the workload profile?", 32),
  makeMsg('fn-general', 'freenode', 'message', 'devopsguru', 'True. I/O bound vs CPU bound makes a huge difference in these benchmarks.', 28),
  makeMsg('fn-general', 'freenode', 'message', 'hackernews', 'Anyone using HTMX in production? Curious about real-world experience.', 20),
  makeMsg('fn-general', 'freenode', 'message', 'goopher', "We switched our internal dashboard to HTMX + Go templates. It's surprisingly productive.", 17),
  makeMsg('fn-general', 'freenode', 'message', 'nodemaster', 'I keep meaning to try it but React muscle memory is hard to break', 14),
  makeMsg('fn-general', 'freenode', 'message', 'typescripter', 'The React Server Components model is essentially the same idea - less client JS', 10),
  makeMsg('fn-general', 'freenode', 'message', 'rustacean', 'Leptos (Rust WASM framework) has an HTMX-like mode too. Best of both worlds.', 5),
  makeMsg('fn-general', 'freenode', 'message', 'pythonicgal', 'So many choices now. Good time to be a web dev!', 2),
]

const freenodeRust: IRCMessage[] = [
  makeMsg('fn-rust', 'freenode', 'system', 'system', 'Channel created on 2024-01-15', 200),
  makeMsg('fn-rust', 'freenode', 'message', 'rustacean', "Cargo workspace question: how do you handle shared types across workspace members?", 90),
  makeMsg('fn-rust', 'freenode', 'message', 'kerneldev', "I create a `common` or `types` crate in the workspace:", 87),
  makeMsg('fn-rust', 'freenode', 'message', 'kerneldev', '```rust\n// Cargo.toml (workspace root)\n[workspace]\nmembers = [\n    "api",\n    "worker",\n    "common",\n]\n\n// common/src/lib.rs\npub mod models {\n    use serde::{Deserialize, Serialize};\n    \n    #[derive(Debug, Clone, Serialize, Deserialize)]\n    pub struct User {\n        pub id: uuid::Uuid,\n        pub email: String,\n        pub created_at: chrono::DateTime<chrono::Utc>,\n    }\n}\n```', 85),
  makeMsg('fn-rust', 'freenode', 'message', 'rustacean', "Perfect, that's clean. Do you publish the common crate or just use path deps?", 82),
  makeMsg('fn-rust', 'freenode', 'message', 'kerneldev', "Path deps for internal stuff. Only publish if it's genuinely reusable across projects.", 80),
  makeMsg('fn-rust', 'freenode', 'message', 'pythonicgal', "Coming from Python, Rust's module system was the hardest part to learn. Worth it though.", 75),
  makeMsg('fn-rust', 'freenode', 'action', 'rustacean', 'agrees - the module system clicks eventually', 72),
  makeMsg('fn-rust', 'freenode', 'message', 'goopher', "Just started learning Rust. The error handling with Result<T, E> is so much better than Go's `if err != nil`", 60),
  makeMsg('fn-rust', 'freenode', 'message', 'rustacean', 'Wait until you discover the `?` operator. Game changer.', 57),
]

const freenodeJS: IRCMessage[] = [
  makeMsg('fn-js', 'freenode', 'message', 'nodemaster', 'Hot take: Bun is production-ready now. We switched and our CI is 3x faster.', 100),
  makeMsg('fn-js', 'freenode', 'message', 'typescripter', 'For running tests sure. But the Node.js compat layer still has gaps.', 97),
  makeMsg('fn-js', 'freenode', 'message', 'hackernews', 'Bun vs Deno vs Node - the eternal frontend debate continues', 94),
  makeMsg('fn-js', 'freenode', 'message', 'nodemaster', "It's not frontend, it's runtime! But yeah lol", 92),
  makeMsg('fn-js', 'freenode', 'message', 'csswhiz', 'Meanwhile I just want `fetch` to work the same everywhere...', 88),
  makeMsg('fn-js', 'freenode', 'message', 'typescripter', '```javascript\n// This is the way\nconst response = await fetch(url, {\n  signal: AbortSignal.timeout(5000),\n});\n\nif (!response.ok) {\n  throw new Error(`HTTP ${response.status}`);\n}\n\nconst data = await response.json();\n```', 85),
  makeMsg('fn-js', 'freenode', 'message', 'nodemaster', 'AbortSignal.timeout is such a nice addition. No more manual AbortController for simple timeouts.', 82),
  makeMsg('fn-js', 'freenode', 'message', 'devopsguru', 'PSA: Node 24 LTS goes EOL next month. Time to upgrade to Node 26.', 70),
  makeMsg('fn-js', 'freenode', 'message', 'hackernews', 'We are still on Node 22 at work... corporate upgrade cycles are brutal', 67),
]

// --- Libera Chat Messages ---
const liberaLinux: IRCMessage[] = [
  makeMsg('lc-linux', 'libera', 'join', 'nixfan', 'nixfan (~nix@flake.host) has joined #linux', 150),
  makeMsg('lc-linux', 'libera', 'message', 'archbtw', 'Just rebuilt my kernel with PGO. Boot time went from 1.2s to 0.8s.', 145),
  makeMsg('lc-linux', 'libera', 'message', 'vimwarrior', 'Is PGO worth the compile time for a desktop kernel though?', 142),
  makeMsg('lc-linux', 'libera', 'message', 'archbtw', '```bash\n# Profile-guided optimization for Linux kernel\n# Step 1: Build with profiling\nmake LLVM=1 KCFLAGS="-fprofile-generate=/tmp/pgo" -j$(nproc)\n\n# Step 2: Boot and run workloads\n# Step 3: Merge profiles\nllvm-profdata merge -o /tmp/pgo/merged.profdata /tmp/pgo/*.profraw\n\n# Step 4: Rebuild with profile data\nmake LLVM=1 KCFLAGS="-fprofile-use=/tmp/pgo/merged.profdata" -j$(nproc)\n```', 140),
  makeMsg('lc-linux', 'libera', 'message', 'emacsgod', 'Nice writeup. I use Gentoo with custom USE flags for similar gains.', 135),
  makeMsg('lc-linux', 'libera', 'message', 'nixfan', "On NixOS I just override the kernel derivation. Reproducible every time.", 130),
  makeMsg('lc-linux', 'libera', 'message', 'dockercapt', 'You kernel guys are wild. I just `docker pull` and call it a day.', 125),
  makeMsg('lc-linux', 'libera', 'action', 'archbtw', 'uses Arch btw', 120),
  makeMsg('lc-linux', 'libera', 'message', 'tmuxer', "Anyone else having issues with the latest nvidia-dkms on 6.12?", 110),
  makeMsg('lc-linux', 'libera', 'message', 'archbtw', "Yeah it's a known issue. Downgrade to 560.35.03 or wait for the fix.", 107),
  makeMsg('lc-linux', 'libera', 'message', 'k8smaster', 'This is why I gave up on nvidia and switched to AMD.', 104),
  makeMsg('lc-linux', 'libera', 'message', 'vimwarrior', '+1 for AMD. Open source drivers just work.', 100),
  makeMsg('lc-linux', 'libera', 'message', 'gitguru', 'Off topic but git 2.48 just added better sparse-checkout performance', 85),
  makeMsg('lc-linux', 'libera', 'message', 'tmuxer', "Nice! Our monorepo checkout was getting painful.", 82),
]

const liberaDevops: IRCMessage[] = [
  makeMsg('lc-devops', 'libera', 'message', 'dockercapt', 'PSA: Docker Hub is changing their rate limits again starting March.', 90),
  makeMsg('lc-devops', 'libera', 'message', 'k8smaster', 'Time to mirror everything to GitHub Container Registry.', 87),
  makeMsg('lc-devops', 'libera', 'message', 'dockercapt', '```yaml\n# docker-compose.yml with registry mirror\nservices:\n  registry:\n    image: registry:2\n    ports:\n      - "5000:5000"\n    environment:\n      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io\n    volumes:\n      - registry-data:/var/lib/registry\n\nvolumes:\n  registry-data:\n```', 85),
  makeMsg('lc-devops', 'libera', 'message', 'devopsguru', 'We use Harbor as our registry. Has built-in vulnerability scanning.', 80),
  makeMsg('lc-devops', 'libera', 'message', 'archbtw', "Podman + Buildah crew checking in. No daemon, no problems.", 75),
  makeMsg('lc-devops', 'libera', 'message', 'k8smaster', '```bash\n# Quick K8s pod debugging\nkubectl run debug --rm -it --image=nicolaka/netshoot -- bash\n\n# Or attach to existing pod network\nkubectl debug -it pod/myapp --image=busybox --target=myapp\n```', 70),
  makeMsg('lc-devops', 'libera', 'message', 'tmuxer', 'netshoot is a lifesaver. Better than installing tools in prod containers.', 67),
  makeMsg('lc-devops', 'libera', 'notice', 'ChanServ', '#devops: Topic is "DevOps, SRE, Platform Engineering | Be kind | No crypto spam"', 60),
]

const liberaVim: IRCMessage[] = [
  makeMsg('lc-vim', 'libera', 'message', 'vimwarrior', 'Neovim 0.12 is fantastic. The new default LSP config is so much simpler.', 80),
  makeMsg('lc-vim', 'libera', 'message', 'emacsgod', 'Emacs has had this for years with eglot :)', 77),
  makeMsg('lc-vim', 'libera', 'message', 'vimwarrior', 'Here we go again...', 75),
  makeMsg('lc-vim', 'libera', 'action', 'archbtw', 'grabs popcorn', 72),
  makeMsg('lc-vim', 'libera', 'message', 'tmuxer', "Can we not? Both are great. I use Helix now anyway.", 70),
  makeMsg('lc-vim', 'libera', 'message', 'gitguru', 'My neovim config if anyone wants it: https://github.com/example/nvim-config', 65),
  makeMsg('lc-vim', 'libera', 'message', 'nixfan', "I manage my neovim config through Nix home-manager. It's beautiful.", 60),
  makeMsg('lc-vim', 'libera', 'message', 'vimwarrior', '```lua\n-- Minimal but powerful neovim setup\nreturn {\n  "neovim/nvim-lspconfig",\n  config = function()\n    local lsp = require("lspconfig")\n    local servers = { "lua_ls", "rust_analyzer", "ts_ls", "gopls" }\n    \n    for _, server in ipairs(servers) do\n      lsp[server].setup({\n        capabilities = require("cmp_nvim_lsp").default_capabilities(),\n      })\n    end\n  end,\n}\n```', 55),
]

// --- EFnet Messages ---
const efnetIRC: IRCMessage[] = [
  makeMsg('ef-irc', 'efnet', 'system', 'system', 'Welcome to #irc on EFnet - the original IRC network', 200),
  makeMsg('ef-irc', 'efnet', 'message', 'oldschool', "Remember when IRC was the only way to chat online? Good times.", 150),
  makeMsg('ef-irc', 'efnet', 'message', 'netadmin', 'IRC never died. It just became niche.', 147),
  makeMsg('ef-irc', 'efnet', 'message', 'scriptkid', 'Matrix/IRC bridges keep the old channels alive at least.', 143),
  makeMsg('ef-irc', 'efnet', 'message', 'perlhacker', "I still write my IRC bots in Perl. Don't judge.", 140),
  makeMsg('ef-irc', 'efnet', 'message', 'rfcreader', "Nothing wrong with Perl. RFC 1459 was implemented in C first but Perl was right behind.", 137),
  makeMsg('ef-irc', 'efnet', 'message', 'bsduser', 'Running ircd on FreeBSD 14 here. Rock solid.', 130),
  makeMsg('ef-irc', 'efnet', 'action', 'oldschool', 'fires up mIRC for nostalgia', 125),
  makeMsg('ef-irc', 'efnet', 'message', 'oldschool', '\x0300,04 \x02EFnet TRIVIA\x02 \x03 Question 12: \x0312What year was IRC invented?\x03 Type your answer!', 123),
  makeMsg('ef-irc', 'efnet', 'message', 'perlhacker', '\x030319\x0388\x03! Jarkko Oikarinen wrote the first IRC server in August 1988', 122),
  makeMsg('ef-irc', 'efnet', 'message', 'oldschool', '\x0303\x02Correct!\x02\x03 \x0306perlhacker\x03 gets \x0308+10 points\x03 (total: \x02\x030960\x03\x02)', 121),
  makeMsg('ef-irc', 'efnet', 'message', 'netadmin', 'These modern web IRC clients are actually pretty nice though.', 120),
  makeMsg('ef-irc', 'efnet', 'message', 'scriptkid', '```python\n# Simple IRC bot in Python\nimport socket\n\ndef irc_bot(server, port, channel, nick):\n    irc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n    irc.connect((server, port))\n    irc.send(f"NICK {nick}\\r\\n".encode())\n    irc.send(f"USER {nick} 0 * :{nick}\\r\\n".encode())\n    irc.send(f"JOIN {channel}\\r\\n".encode())\n    \n    while True:\n        data = irc.recv(2048).decode()\n        if data.startswith("PING"):\n            irc.send(f"PONG {data.split()[1]}\\r\\n".encode())\n\nirc_bot("irc.efnet.org", 6667, "#irc", "mybot")\n```', 115),
  makeMsg('ef-irc', 'efnet', 'message', 'perlhacker', "No error handling? Bold strategy.", 112),
  makeMsg('ef-irc', 'efnet', 'message', 'scriptkid', "It's an example! Production code would have proper error handling obviously.", 110),
  makeMsg('ef-irc', 'efnet', 'message', 'rfcreader', "You should also handle CTCP VERSION requests. It's polite.", 105),
  makeMsg('ef-irc', 'efnet', 'kick', 'system', 'spambot42 was kicked by netadmin: No spam allowed', 103),
  makeMsg('ef-irc', 'efnet', 'nick_change', 'bsduser', 'bsduser is now known as bsduser_away', 101),
  makeMsg('ef-irc', 'efnet', 'message', 'oldschool', 'Check out this classic IRC screenshot: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Irssi_screen.png/300px-Irssi_screen.png', 100),
]

const efnetSecurity: IRCMessage[] = [
  makeMsg('ef-security', 'efnet', 'message', 'netadmin', 'New OpenSSL CVE just dropped. Patch your servers.', 60),
  makeMsg('ef-security', 'efnet', 'message', 'oldschool', 'Again?! What is it this time?', 57),
  makeMsg('ef-security', 'efnet', 'message', 'netadmin', 'Buffer overflow in the X.509 name constraint checking. High severity.', 55),
  makeMsg('ef-security', 'efnet', 'message', 'bsduser', "LibreSSL gang stays winning. We forked for a reason.", 52),
  makeMsg('ef-security', 'efnet', 'message', 'rfcreader', '```bash\n# Quick check for vulnerable OpenSSL versions\nopenssl version -a\n\n# Patch on Debian/Ubuntu\nsudo apt update && sudo apt upgrade openssl libssl3\n\n# Verify the fix\nopenssl version\n```', 48),
  makeMsg('ef-security', 'efnet', 'message', 'perlhacker', 'Already patched. Automated updates FTW.', 45),
  makeMsg('ef-security', 'efnet', 'message', 'scriptkid', 'Automated security updates on prod servers? Brave.', 42),
  makeMsg('ef-security', 'efnet', 'message', 'netadmin', 'Automated updates + canary deployments. Not that brave.', 40),
]

const efnetDM: IRCMessage[] = [
  makeMsg('ef-dm-oldschool', 'efnet', 'message', 'oldschool', 'Hey, you around? Want to discuss the server migration.', 30),
  makeMsg('ef-dm-oldschool', 'efnet', 'message', 'You', 'Yeah, what are you thinking?', 28),
  makeMsg('ef-dm-oldschool', 'efnet', 'message', 'oldschool', "We need to move to the new hosting provider by end of month. Can you handle the DNS cutover?", 25),
  makeMsg('ef-dm-oldschool', 'efnet', 'message', 'You', 'Sure, I can do it this weekend during the maintenance window.', 22),
  makeMsg('ef-dm-oldschool', 'efnet', 'message', 'oldschool', 'Perfect. Low TTL on the records first, then we switch.', 20),
]

// --- Build Channels ---
function buildChannel(
  id: string,
  serverId: string,
  name: string,
  topic: string,
  messages: IRCMessage[],
  users: IRCUser[],
  isDM = false,
  unread = 0,
  mentions = 0
): IRCChannel {
  return {
    id,
    serverId,
    name,
    topic,
    topicSetBy: isDM ? undefined : users[0]?.nickname,
    messages,
    users: isDM ? [] : users,
    unreadCount: unread,
    mentionCount: mentions,
    isDirectMessage: isDM,
    joined: true,
    showJoinPart: true,
    modes: isDM ? '' : '+nst',
  }
}

export const mockServers: IRCServer[] = [
  {
    id: 'freenode',
    name: 'Freenode',
    host: 'irc.freenode.net',
    port: 6697,
    ssl: true,
    autoConnect: true,
    nickname: 'patchcord',
    username: 'patchcord',
    realName: 'Patchcord User',
    password: undefined,
    saslEnabled: true,
    saslUsername: 'patchcord',
    saslPassword: '***',
    autoJoinChannels: ['#general', '#rust', '#javascript'],
    onJoinCommands: ['/msg NickServ IDENTIFY devuser p4ssw0rd', '/mode devuser +x'],
    status: 'connected',
    channels: [
      buildChannel('fn-general', 'freenode', '#general', 'General programming discussion | Be respectful | No spam', freenodeGeneral, freenodeUsers, false, 0, 0),
      buildChannel('fn-rust', 'freenode', '#rust', 'Rust programming language | cargo is love | RTFM: doc.rust-lang.org', freenodeRust, freenodeUsers.slice(0, 6), false, 3, 0),
      buildChannel('fn-js', 'freenode', '#javascript', 'JavaScript & TypeScript | Node.js | Deno | Bun | Web Standards', freenodeJS, freenodeUsers.slice(1, 8), false, 5, 1),
    ],
    serverMessages: [
      makeMsg('', 'freenode', 'notice', 'irc.freenode.net', '*** Looking up your hostname...', 120),
      makeMsg('', 'freenode', 'notice', 'irc.freenode.net', '*** Found your hostname (user/devuser)', 120),
      makeMsg('', 'freenode', 'notice', 'irc.freenode.net', '*** Checking Ident', 119),
      makeMsg('', 'freenode', 'system', 'system', 'Welcome to the Freenode Internet Relay Chat Network devuser', 118),
      makeMsg('', 'freenode', 'system', 'system', 'Your host is irc.freenode.net, running version ircd-7.2.3', 118),
      makeMsg('', 'freenode', 'system', 'system', 'This server was created 2024-01-15 08:30:00 UTC', 118),
      makeMsg('', 'freenode', 'system', 'system', '--- Message of the Day ---', 117),
      makeMsg('', 'freenode', 'system', 'system', '  ___                          _      ', 117),
      makeMsg('', 'freenode', 'system', 'system', ' / __| __ ___ ___ _ _  ___  __| | ___ ', 117),
      makeMsg('', 'freenode', 'system', 'system', ' \\__ \\/ _/ -_) -_) \' \\/ _ \\/ _` |/ -_)', 117),
      makeMsg('', 'freenode', 'system', 'system', ' |___/\\__\\___|___|_||_\\___/\\__,_|\\___|', 117),
      makeMsg('', 'freenode', 'system', 'system', '', 117),
      makeMsg('', 'freenode', 'system', 'system', 'Welcome to Freenode! Please read our policies at', 116),
      makeMsg('', 'freenode', 'system', 'system', 'https://freenode.net/policies - Be respectful.', 116),
      makeMsg('', 'freenode', 'system', 'system', 'For help, join #freenode or see /msg NickServ HELP', 116),
      makeMsg('', 'freenode', 'system', 'system', '--- End of Message of the Day ---', 115),
      makeMsg('', 'freenode', 'notice', 'NickServ', 'You are now identified for devuser', 115),
      makeMsg('', 'freenode', 'system', 'system', 'Mode change [+x] for user devuser', 114),
      makeMsg('', 'freenode', 'system', 'system', 'There are 4832 users and 12847 invisible on 32 servers', 114),
      makeMsg('', 'freenode', 'system', 'system', '28 operator(s) online', 114),
      makeMsg('', 'freenode', 'system', 'system', '15203 channels formed', 114),
    ],
    latency: 42,
    collapsed: false,
    awayMessage: '',
  },
  {
    id: 'libera',
    name: 'Libera Chat',
    host: 'irc.libera.chat',
    port: 6697,
    ssl: true,
    autoConnect: true,
    nickname: 'patchcord',
    username: 'patchcord',
    realName: 'Patchcord User',
    password: undefined,
    saslEnabled: false,
    autoJoinChannels: ['#linux', '#devops', '#vim'],
    onJoinCommands: [],
    status: 'connected',
    channels: [
      buildChannel('lc-linux', 'libera', '#linux', 'Linux discussion | kernel.org | No distro wars (we all know its Arch)', liberaLinux, libera1Users, false, 7, 2),
      buildChannel('lc-devops', 'libera', '#devops', 'DevOps, SRE, Platform Engineering | Be kind | No crypto spam', liberaDevops, libera1Users.slice(0, 6), false, 0, 0),
      buildChannel('lc-vim', 'libera', '#vim', 'Vim & Neovim | :wq | The eternal editor', liberaVim, libera1Users.slice(1, 7), false, 2, 0),
    ],
    serverMessages: [
      makeMsg('', 'libera', 'notice', 'irc.libera.chat', '*** Looking up your hostname...', 90),
      makeMsg('', 'libera', 'notice', 'irc.libera.chat', '*** Found your hostname', 90),
      makeMsg('', 'libera', 'system', 'system', 'Welcome to the Libera.Chat Internet Relay Chat Network devuser', 89),
      makeMsg('', 'libera', 'system', 'system', 'Your host is irc.libera.chat, running version solanum-1.0', 89),
      makeMsg('', 'libera', 'system', 'system', '--- Message of the Day ---', 88),
      makeMsg('', 'libera', 'system', 'system', 'Welcome to Libera Chat, a next-generation IRC network', 88),
      makeMsg('', 'libera', 'system', 'system', 'for free & open-source software communities.', 88),
      makeMsg('', 'libera', 'system', 'system', 'Website: https://libera.chat  Docs: https://libera.chat/guides', 87),
      makeMsg('', 'libera', 'system', 'system', '--- End of Message of the Day ---', 87),
      makeMsg('', 'libera', 'system', 'system', 'There are 7241 users and 31502 invisible on 25 servers', 86),
      makeMsg('', 'libera', 'system', 'system', '42 operator(s) online, 22561 channels formed', 86),
    ],
    latency: 28,
    collapsed: false,
    awayMessage: '',
  },
  {
    id: 'efnet',
    name: 'EFnet',
    host: 'irc.efnet.org',
    port: 6667,
    ssl: false,
    autoConnect: true,
    nickname: 'patchcord',
    username: 'patchcord',
    realName: 'Patchcord User',
    password: undefined,
    saslEnabled: false,
    autoJoinChannels: ['#irc', '#security'],
    onJoinCommands: ['/msg NickServ GHOST devuser p4ssw0rd'],
    status: 'connecting',
    channels: [
      buildChannel('ef-irc', 'efnet', '#irc', 'IRC meta discussion | The original chat protocol | RFC 1459', efnetIRC, efnetUsers, false, 12, 0),
      buildChannel('ef-security', 'efnet', '#security', 'InfoSec discussion | CVEs | Responsible disclosure only', efnetSecurity, efnetUsers.slice(0, 5), false, 4, 1),
      buildChannel('ef-dm-oldschool', 'efnet', 'oldschool', '', efnetDM, [efnetUsers[0]], true, 1, 1),
    ],
    serverMessages: [
      makeMsg('', 'efnet', 'notice', 'irc.efnet.org', '*** Looking up your hostname...', 60),
      makeMsg('', 'efnet', 'notice', 'irc.efnet.org', '*** Checking Ident', 60),
      makeMsg('', 'efnet', 'system', 'system', 'Connecting to irc.efnet.org (208.185.127.34) port 6667...', 59),
      makeMsg('', 'efnet', 'system', 'system', 'Welcome to EFnet - the original IRC network', 58),
      makeMsg('', 'efnet', 'system', 'system', '--- Message of the Day ---', 58),
      makeMsg('', 'efnet', 'system', 'system', 'EFnet - Where IRC began. No services, no frills.', 57),
      makeMsg('', 'efnet', 'system', 'system', 'Admins: admin@efnet.org | Abuse: abuse@efnet.org', 57),
      makeMsg('', 'efnet', 'system', 'system', '--- End of Message of the Day ---', 56),
    ],
    latency: 115,
    collapsed: false,
    awayMessage: '',
  },
]

export const defaultSettings = {
  theme: 'dark' as const,
  colorTheme: 'default-dark' as const,
  fontSize: 14,
  messageDensity: 'cozy' as const,
  timestampFormat: '24h' as const,
  showJoinPartQuit: true,
  showStatusPrefixesInChat: true,
  accentColor: '#22c55e',
  uiFontPreset: 'default' as const,
  monoFontPreset: 'default' as const,
  desktopNotifications: true,
  notificationSounds: true,
  highlightWords: ['patchcord'],
  dmNotifications: true,
  maxScrollbackLines: 5000,
  inlineImagePreviews: true,
  linkPreviews: true,
  syntaxHighlighting: true,
  ircColors: true,
  nickColorScheme: 'default' as const,
  avatarUrl: '',
  defaultNickname: 'patchcord',
  fallbackNicknames: ['patchcord_', 'patchcord__'],
  defaultUsername: 'patchcord',
  defaultRealName: 'Patchcord User',
  ignoreList: [] as string[],
  quitMessage: 'Patchcord - https://patchcord.dev',
  autoReconnect: true,
  autoReconnectDelay: 5,
  encoding: 'UTF-8',
  showRawLog: false,
  saveAllLogs: false,
  keybindings: {
    'toggle-sidebar': 'Alt+B',
    'toggle-userlist': 'Alt+U',
    'open-settings': 'Alt+S',
    'server-1': 'Alt+1',
    'server-2': 'Alt+2',
    'server-3': 'Alt+3',
    'search': 'Ctrl+F',
    'next-channel': 'Alt+Down',
    'prev-channel': 'Alt+Up',
  },
}
