export type TerminalThemeId =
  | 'default-dark'
  | 'default-light'
  | 'dracula'
  | 'nord'
  | 'solarized-dark'
  | 'monokai'
  | 'gruvbox-dark'
  | 'tokyo-night'
  | 'catppuccin-mocha'
  | 'one-dark'
  | 'github-dark'
  | 'rose-pine'

export interface TerminalTheme {
  id: TerminalThemeId
  name: string
  description: string
  isDark: boolean
  /** Shiki theme name to use for syntax highlighting */
  shikiTheme: string
  colors: {
    background: string
    foreground: string
    card: string
    cardForeground: string
    primary: string
    primaryForeground: string
    secondary: string
    secondaryForeground: string
    muted: string
    mutedForeground: string
    border: string
    accent: string
    accentForeground: string
    surface: string
    surfaceForeground: string
    /** Sidebar specific */
    sidebarBg: string
    sidebarFg: string
    sidebarBorder: string
    /** Code block chrome */
    codeBackground: string
    codeChrome: string
  }
  /** Preview swatch colors for the theme selector */
  swatches: [string, string, string, string, string]
}

export const terminalThemes: TerminalTheme[] = [
  {
    id: 'default-dark',
    name: 'Default Dark',
    description: 'The default Patchcord dark theme',
    isDark: true,
    shikiTheme: 'github-dark-default',
    colors: {
      background: '#141820',
      foreground: '#dce1ea',
      card: '#1a1f2b',
      cardForeground: '#dce1ea',
      primary: '#34d27b',
      primaryForeground: '#141820',
      secondary: '#252a36',
      secondaryForeground: '#dce1ea',
      muted: '#212633',
      mutedForeground: '#7e8594',
      border: '#2a2f3b',
      accent: '#34d27b',
      accentForeground: '#141820',
      surface: '#1c2129',
      surfaceForeground: '#dce1ea',
      sidebarBg: '#10141b',
      sidebarFg: '#dce1ea',
      sidebarBorder: '#2a2f3b',
      codeBackground: '#0d1117',
      codeChrome: '#161b22',
    },
    swatches: ['#141820', '#34d27b', '#dce1ea', '#1a1f2b', '#7e8594'],
  },
  {
    id: 'default-light',
    name: 'Default Light',
    description: 'The default Patchcord light theme',
    isDark: false,
    shikiTheme: 'github-light-default',
    colors: {
      background: '#f5f6f8',
      foreground: '#1a1f2b',
      card: '#eceef2',
      cardForeground: '#1a1f2b',
      primary: '#28a864',
      primaryForeground: '#ffffff',
      secondary: '#e2e5ea',
      secondaryForeground: '#1a1f2b',
      muted: '#e6e8ec',
      mutedForeground: '#636b78',
      border: '#d4d8df',
      accent: '#28a864',
      accentForeground: '#ffffff',
      surface: '#e9ebef',
      surfaceForeground: '#1a1f2b',
      sidebarBg: '#eceef2',
      sidebarFg: '#1a1f2b',
      sidebarBorder: '#d4d8df',
      codeBackground: '#f6f8fa',
      codeChrome: '#ebedf0',
    },
    swatches: ['#f5f6f8', '#28a864', '#1a1f2b', '#eceef2', '#636b78'],
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'A dark theme with vibrant purples and pinks',
    isDark: true,
    shikiTheme: 'dracula',
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      card: '#2d303e',
      cardForeground: '#f8f8f2',
      primary: '#bd93f9',
      primaryForeground: '#282a36',
      secondary: '#343746',
      secondaryForeground: '#f8f8f2',
      muted: '#313445',
      mutedForeground: '#6272a4',
      border: '#3b3f51',
      accent: '#ff79c6',
      accentForeground: '#282a36',
      surface: '#2f3241',
      surfaceForeground: '#f8f8f2',
      sidebarBg: '#21222c',
      sidebarFg: '#f8f8f2',
      sidebarBorder: '#3b3f51',
      codeBackground: '#1e1f29',
      codeChrome: '#282a36',
    },
    swatches: ['#282a36', '#bd93f9', '#ff79c6', '#50fa7b', '#f8f8f2'],
  },
  {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic, north-bluish clean theme',
    isDark: true,
    shikiTheme: 'nord',
    colors: {
      background: '#2e3440',
      foreground: '#d8dee9',
      card: '#333a47',
      cardForeground: '#d8dee9',
      primary: '#88c0d0',
      primaryForeground: '#2e3440',
      secondary: '#3b4252',
      secondaryForeground: '#d8dee9',
      muted: '#373e4d',
      mutedForeground: '#7b88a1',
      border: '#434c5e',
      accent: '#81a1c1',
      accentForeground: '#2e3440',
      surface: '#353c4a',
      surfaceForeground: '#d8dee9',
      sidebarBg: '#272c36',
      sidebarFg: '#d8dee9',
      sidebarBorder: '#434c5e',
      codeBackground: '#242933',
      codeChrome: '#2e3440',
    },
    swatches: ['#2e3440', '#88c0d0', '#81a1c1', '#a3be8c', '#d8dee9'],
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    description: 'Precision colors for machines and people',
    isDark: true,
    shikiTheme: 'solarized-dark',
    colors: {
      background: '#002b36',
      foreground: '#839496',
      card: '#073642',
      cardForeground: '#839496',
      primary: '#268bd2',
      primaryForeground: '#fdf6e3',
      secondary: '#0a3d4a',
      secondaryForeground: '#93a1a1',
      muted: '#083845',
      mutedForeground: '#586e75',
      border: '#174b59',
      accent: '#2aa198',
      accentForeground: '#fdf6e3',
      surface: '#063845',
      surfaceForeground: '#93a1a1',
      sidebarBg: '#001f27',
      sidebarFg: '#839496',
      sidebarBorder: '#174b59',
      codeBackground: '#00212b',
      codeChrome: '#002b36',
    },
    swatches: ['#002b36', '#268bd2', '#2aa198', '#b58900', '#839496'],
  },
  {
    id: 'monokai',
    name: 'Monokai',
    description: 'Classic warm dark theme from Sublime Text',
    isDark: true,
    shikiTheme: 'monokai',
    colors: {
      background: '#272822',
      foreground: '#f8f8f2',
      card: '#2d2e27',
      cardForeground: '#f8f8f2',
      primary: '#a6e22e',
      primaryForeground: '#272822',
      secondary: '#3e3d32',
      secondaryForeground: '#f8f8f2',
      muted: '#383930',
      mutedForeground: '#75715e',
      border: '#49483e',
      accent: '#f92672',
      accentForeground: '#f8f8f2',
      surface: '#33342b',
      surfaceForeground: '#f8f8f2',
      sidebarBg: '#1e1f1c',
      sidebarFg: '#f8f8f2',
      sidebarBorder: '#49483e',
      codeBackground: '#1d1e19',
      codeChrome: '#272822',
    },
    swatches: ['#272822', '#a6e22e', '#f92672', '#66d9ef', '#f8f8f2'],
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    description: 'Retro groove color scheme with warm tones',
    isDark: true,
    shikiTheme: 'vitesse-dark',
    colors: {
      background: '#282828',
      foreground: '#ebdbb2',
      card: '#2e2c2a',
      cardForeground: '#ebdbb2',
      primary: '#b8bb26',
      primaryForeground: '#282828',
      secondary: '#3c3836',
      secondaryForeground: '#ebdbb2',
      muted: '#363230',
      mutedForeground: '#928374',
      border: '#504945',
      accent: '#fe8019',
      accentForeground: '#282828',
      surface: '#32302f',
      surfaceForeground: '#ebdbb2',
      sidebarBg: '#1d2021',
      sidebarFg: '#ebdbb2',
      sidebarBorder: '#504945',
      codeBackground: '#1d2021',
      codeChrome: '#282828',
    },
    swatches: ['#282828', '#b8bb26', '#fe8019', '#fb4934', '#ebdbb2'],
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    description: 'A clean dark theme celebrating city lights',
    isDark: true,
    shikiTheme: 'tokyo-night',
    colors: {
      background: '#1a1b26',
      foreground: '#a9b1d6',
      card: '#1f2030',
      cardForeground: '#a9b1d6',
      primary: '#7aa2f7',
      primaryForeground: '#1a1b26',
      secondary: '#24283b',
      secondaryForeground: '#a9b1d6',
      muted: '#222436',
      mutedForeground: '#565f89',
      border: '#2f3350',
      accent: '#bb9af7',
      accentForeground: '#1a1b26',
      surface: '#1e1f30',
      surfaceForeground: '#a9b1d6',
      sidebarBg: '#16161e',
      sidebarFg: '#a9b1d6',
      sidebarBorder: '#2f3350',
      codeBackground: '#13131a',
      codeChrome: '#1a1b26',
    },
    swatches: ['#1a1b26', '#7aa2f7', '#bb9af7', '#9ece6a', '#a9b1d6'],
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    description: 'Soothing pastel theme for the high-spirited',
    isDark: true,
    shikiTheme: 'catppuccin-mocha',
    colors: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      card: '#232334',
      cardForeground: '#cdd6f4',
      primary: '#cba6f7',
      primaryForeground: '#1e1e2e',
      secondary: '#2a2a3c',
      secondaryForeground: '#cdd6f4',
      muted: '#262637',
      mutedForeground: '#6c7086',
      border: '#353548',
      accent: '#f5c2e7',
      accentForeground: '#1e1e2e',
      surface: '#212133',
      surfaceForeground: '#cdd6f4',
      sidebarBg: '#181825',
      sidebarFg: '#cdd6f4',
      sidebarBorder: '#353548',
      codeBackground: '#151521',
      codeChrome: '#1e1e2e',
    },
    swatches: ['#1e1e2e', '#cba6f7', '#f5c2e7', '#a6e3a1', '#cdd6f4'],
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    description: 'Atom editor classic dark theme',
    isDark: true,
    shikiTheme: 'one-dark-pro',
    colors: {
      background: '#282c34',
      foreground: '#abb2bf',
      card: '#2c313a',
      cardForeground: '#abb2bf',
      primary: '#61afef',
      primaryForeground: '#282c34',
      secondary: '#323842',
      secondaryForeground: '#abb2bf',
      muted: '#2e343e',
      mutedForeground: '#636d83',
      border: '#3e4452',
      accent: '#c678dd',
      accentForeground: '#282c34',
      surface: '#2e343c',
      surfaceForeground: '#abb2bf',
      sidebarBg: '#21252b',
      sidebarFg: '#abb2bf',
      sidebarBorder: '#3e4452',
      codeBackground: '#1e2227',
      codeChrome: '#282c34',
    },
    swatches: ['#282c34', '#61afef', '#c678dd', '#98c379', '#abb2bf'],
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    description: 'GitHub official dark theme',
    isDark: true,
    shikiTheme: 'github-dark',
    colors: {
      background: '#0d1117',
      foreground: '#e6edf3',
      card: '#131920',
      cardForeground: '#e6edf3',
      primary: '#58a6ff',
      primaryForeground: '#0d1117',
      secondary: '#1a2231',
      secondaryForeground: '#e6edf3',
      muted: '#161d27',
      mutedForeground: '#7d8590',
      border: '#21262d',
      accent: '#3fb950',
      accentForeground: '#0d1117',
      surface: '#111820',
      surfaceForeground: '#e6edf3',
      sidebarBg: '#090d13',
      sidebarFg: '#e6edf3',
      sidebarBorder: '#21262d',
      codeBackground: '#090d13',
      codeChrome: '#0d1117',
    },
    swatches: ['#0d1117', '#58a6ff', '#3fb950', '#f78166', '#e6edf3'],
  },
  {
    id: 'rose-pine',
    name: 'Rose Pine',
    description: 'All natural pine, faux fur and a bit of soho vibes',
    isDark: true,
    shikiTheme: 'rose-pine',
    colors: {
      background: '#191724',
      foreground: '#e0def4',
      card: '#1f1d2e',
      cardForeground: '#e0def4',
      primary: '#c4a7e7',
      primaryForeground: '#191724',
      secondary: '#26233a',
      secondaryForeground: '#e0def4',
      muted: '#232136',
      mutedForeground: '#6e6a86',
      border: '#312e46',
      accent: '#ebbcba',
      accentForeground: '#191724',
      surface: '#1e1c30',
      surfaceForeground: '#e0def4',
      sidebarBg: '#14121f',
      sidebarFg: '#e0def4',
      sidebarBorder: '#312e46',
      codeBackground: '#11101d',
      codeChrome: '#191724',
    },
    swatches: ['#191724', '#c4a7e7', '#ebbcba', '#9ccfd8', '#e0def4'],
  },
]

export function getThemeById(id: TerminalThemeId): TerminalTheme {
  return terminalThemes.find((t) => t.id === id) ?? terminalThemes[0]
}
